apache/openserverless-operator

DISCLAIMER, NOTICE, Taskfile.yml
Updated version tag and added DISCLAIMER and NOTICE file for incubating ASF projects
=> Implements apache/openserverless#22

.github/workflows/image.yml, Dockerfile, Taskfile.yml, nuvolaris/actionexecutor.py
this PR fix a small glitch into the internal OpenServerless Action Executor.
=> fix cron scheduler

.github/workflows/image.yml
GitHub actions for image push to apache repo
=> GitHub actions for image push to apache repo

.gitignore, deploy/cuda/cuda.yaml, deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml, nuvolaris/operator_util.py, nuvolaris/whisk_actions_deployer.py, tests/pytorch.py
This PR contributes an improvement into the operator to annotate the deployment status of the system action into the config ConfigMap.
There are two possible values for the `system_action_status` annotation
- created
- failed
When `created` the operator ensure that the system action have been deployed successfully and therefore it is possible to safely invoke them. This has been introduced to provide a way to ensure that the command `ops setup nuvolaris login` can be safely executed.
=> Annotate status of system action deployment

nuvolaris/openwhisk.py
adds retry to cm config map annotation
=> fix: adds retry to cm config map annotation

.github/workflows/check.yml, deploy/demos/reference/milvus_manifest.yaml, deploy/milvus-operator/README.md, nuvolaris/templates/opaque-secret-tpl.yaml
Added missing license in files and make license check breaking in Github check action and the image build one.
=> fix licence issues

nuvolaris/etcd.py, nuvolaris/milvus_standalone.py
milvus undeploy crash when deleting wsk/controller
=> fix: milvus undeploy crash when deleting wsk/controller

.github/workflows/check.yml, .github/workflows/image.yml
This PR fixes some ASF license headers still reporting obsolete copyright reference.
=> Fix for apache/openserverless#83

.github/workflows/check.yml
Added the missing python setup action also in check.yml (which use the cisetup.sh)
=> chore(gh): added setup python 3.12 in check.yml

nuvolaris/certmanager.py, nuvolaris/etcd.py, nuvolaris/ingress.py, nuvolaris/milvus_operator.py, nuvolaris/milvus_standalone.py, nuvolaris/monitoring.py, nuvolaris/operator_util.py, nuvolaris/template.py, nuvolaris/user_handlers.py, nuvolaris/util.py, tests/couchdb_test.ipy, tests/k3s/ingress_test.ipy, tests/kafka_test.ipy, tests/kind/mongodb_std_test.ipy, tests/kind/mongodb_user_test.ipy, tests/kind/nuvolaris_subject_test.ipy, tests/kvrocks_user_test.ipy, tests/microk8s/ingress_test.ipy, tests/workflows_test.ipy, tools/cli/wsk/wskadmin.py
These commits fix issues resulting from the upgrade to python 3.12
=> Fix in raw strings and testing

Dockerfile
removed the deletion of deploy.tar
=> chore(operator): fix Dockerfile

.github/workflows/check.yml
This PR re-activate the task itest execution into the check.yml GH action.
=> re-activate itest in check GH action

actions/Taskfile.yml, actions/login/__main__.py, deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml, nuvolaris/bcrypt_util.py, nuvolaris/nuvolaris_metadata.py, nuvolaris/operator_util.py, nuvolaris/user_metadata.py, nuvolaris/userdb_util.py, poetry.lock, pyproject.toml, tests/kind/bcrypt_util_test.ipy, tests/kind/userdb_util_test.ipy, tests/kind/whisk.yaml, whisk-system.sh
Hashed password inside couchdb using bcrypt with cost 12
=> feat(operator): bcrypt hashed passwords

nuvolaris/milvus_admin_client.py, nuvolaris/milvus_simple_client.py, tests/kind/whisk.yaml
replaced old permissions with DatabaseAdmin and CollectionAdmin implemented the rest api  grantV2 and revokeV2
=> fix(milvus): milvus 2.5.2 permissions

nuvolaris/milvus_standalone.py, tests/kind/milvus_standalone_test.ipy
extended tests for milvus_standalone.py
=> more milvus tests

actions/login/__main__.py, actions/secrets/__main__.py, actions/secrets/flatdict.py, actions/secrets/user_metadata.py, actions/system.yml, nuvolaris/couchdb.py, nuvolaris/whisk_actions_deployer.py
added a "secret" system action to handle secrets add and remove.
=> feat(actions): added secrets system action

.github/workflows/image.yml
trying with v9.2.0-48 (previous latest)
=> chore: try to fix gh build action

actions/devel/psql/__main__.py, actions/devel/psql/command/psql.py
Fixed the invalid json from psql system action. See https://github.com/apache/openserverless/issues/100
=> fix(operator): invalid json in psql

actions/devel/ferretdb/command/ferretbd.py
Fixed the invalid json from ferretdb system action. As per psql, see https://github.com/apache/openserverless/issues/100
=> fix(operator): invalid json in ferretdb

actions/common/util.py, actions/devel/ferretdb/__main__.py, actions/devel/ferretdb/common/util.py, actions/devel/minio/__main__.py, actions/devel/minio/common/util.py, actions/devel/psql/__main__.py, actions/devel/psql/command/psql.py, actions/devel/psql/common/util.py, actions/devel/redis/__main__.py, actions/devel/redis/common/util.py
Devel system actions will add content-type: application/json header if returned content is json
=> chore(operator): content-type json

deploy/nuvolaris-permissions/whisk-crd.yaml, nuvolaris/milvus_admin_client.py, nuvolaris/milvus_standalone.py, nuvolaris/templates/etcd-sts.yaml, nuvolaris/util.py, tests/kind/milvus_standalone_test.ipy, tests/kind/whisk-full.yaml
Added quota and auto-compaction parameters
Fixed some bugs in milvus setup and tests
=> Etcd parameters and milvus setup

nuvolaris/apihost_util.py
removed two lines that forced apihost "localhost" in kind
=> fix: remove apihost ovverride in kind

deploy/demos/reference/milvus_manifest.yaml, nuvolaris/templates/01-minio-dep.yaml, nuvolaris/templates/etcd-sts.yaml
replaced minio image because the bitnami is actually not available anymore
=> fix: replaced minio image
